name: Main CI
on:
  - push
  - pull_request
jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.0.19"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@e232f72a4330a07aae8418e8aa56b64efcdda636
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Check Lint
        run: composer run lint
  cs:
    name: Code Style Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.0.19"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@e232f72a4330a07aae8418e8aa56b64efcdda636
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Check Code Style
        run: composer run cs
  unit-test:
    name: Unit Tests Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.0.19"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@e232f72a4330a07aae8418e8aa56b64efcdda636
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
      - name: Install Dependencies
        run: composer install --ignore-platform-reqs
      - name: Check Unit Tests
        run: composer run test
